<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.5-dev (doctrine2-annotation) on 2014-12-07 18:21:29.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace FootBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * FootBundle\Entity\Imgmatchcom
 *
 * @ORM\Entity(repositoryClass="ImgmatchcomRepository")
 * @ORM\Table(name="imgmatchcom", indexes={@ORM\Index(name="fk_img_comment1_idx", columns={"comment_id"})})
 */
class Imgmatchcom
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="`name`", type="string", length=45)
     */
    protected $name;

    /**
     * @ORM\Column(type="integer")
     */
    protected $comment_id;

    /**
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $description;

    /**
     * @ORM\ManyToOne(targetEntity="Matchcom", inversedBy="imgmatchcoms")
     * @ORM\JoinColumn(name="comment_id", referencedColumnName="id")
     */
    protected $matchcom;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \FootBundle\Entity\Imgmatchcom
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \FootBundle\Entity\Imgmatchcom
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of comment_id.
     *
     * @param integer $comment_id
     * @return \FootBundle\Entity\Imgmatchcom
     */
    public function setCommentId($comment_id)
    {
        $this->comment_id = $comment_id;

        return $this;
    }

    /**
     * Get the value of comment_id.
     *
     * @return integer
     */
    public function getCommentId()
    {
        return $this->comment_id;
    }

    /**
     * Set the value of description.
     *
     * @param string $description
     * @return \FootBundle\Entity\Imgmatchcom
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get the value of description.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set Matchcom entity (many to one).
     *
     * @param \FootBundle\Entity\Matchcom $matchcom
     * @return \FootBundle\Entity\Imgmatchcom
     */
    public function setMatchcom(Matchcom $matchcom = null)
    {
        $this->matchcom = $matchcom;

        return $this;
    }

    /**
     * Get Matchcom entity (many to one).
     *
     * @return \FootBundle\Entity\Matchcom
     */
    public function getMatchcom()
    {
        return $this->matchcom;
    }

    public function __sleep()
    {
        return array('id', 'name', 'comment_id', 'description');
    }
}
