<?php

namespace FootBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImgteamcomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgteamcomRepository extends EntityRepository
{
}
