<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 2.1.5-dev (doctrine2-annotation) on 2014-12-07 18:21:30.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace FootBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * FootBundle\Entity\MatchHasUser
 *
 * @ORM\Entity(repositoryClass="MatchHasUserRepository")
 * @ORM\Table(name="match_has_user", indexes={@ORM\Index(name="fk_match_has_user_user2_idx", columns={"user_id"}), @ORM\Index(name="fk_match_has_user_match2_idx", columns={"match_id"})})
 */
class MatchHasUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $entree;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $sortie;

    /**
     * @ORM\ManyToOne(targetEntity="Match", inversedBy="matchHasUsers")
     * @ORM\JoinColumn(name="match_id", referencedColumnName="id")
     */
    protected $match;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="matchHasUsers")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $user;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \FootBundle\Entity\MatchHasUser
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of entree.
     *
     * @param integer $entree
     * @return \FootBundle\Entity\MatchHasUser
     */
    public function setEntree($entree)
    {
        $this->entree = $entree;

        return $this;
    }

    /**
     * Get the value of entree.
     *
     * @return integer
     */
    public function getEntree()
    {
        return $this->entree;
    }

    /**
     * Set the value of sortie.
     *
     * @param integer $sortie
     * @return \FootBundle\Entity\MatchHasUser
     */
    public function setSortie($sortie)
    {
        $this->sortie = $sortie;

        return $this;
    }

    /**
     * Get the value of sortie.
     *
     * @return integer
     */
    public function getSortie()
    {
        return $this->sortie;
    }

    /**
     * Set Match entity (many to one).
     *
     * @param \FootBundle\Entity\Match $match
     * @return \FootBundle\Entity\MatchHasUser
     */
    public function setMatch(Match $match = null)
    {
        $this->match = $match;

        return $this;
    }

    /**
     * Get Match entity (many to one).
     *
     * @return \FootBundle\Entity\Match
     */
    public function getMatch()
    {
        return $this->match;
    }

    /**
     * Set User entity (many to one).
     *
     * @param \FootBundle\Entity\User $user
     * @return \FootBundle\Entity\MatchHasUser
     */
    public function setUser(User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get User entity (many to one).
     *
     * @return \FootBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    public function __sleep()
    {
        return array('id', 'match_id', 'user_id', 'entree', 'sortie');
    }
}
