<?php

namespace FootBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchHasUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchHasUserRepository extends EntityRepository
{
}
