<?php

namespace FootBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchHasButeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchHasButeurRepository extends EntityRepository
{
}
