<?php

namespace FootBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoringRepository extends EntityRepository
{
}
