<?php

namespace FootBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamcomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamcomRepository extends EntityRepository
{
}
