imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        dbname: %database_name%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: FootBundle\Entity\User
    from_email:
        address:        hamswb@free.fr
        sender_name:    Admin
    registration:
        form:
            type: app_user_registration
            validation_groups:  [Default]
    profile:
        form:
            type: app_user_profile
            validation_groups:  [Default]

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        club_adapter_image:
            local:
                directory: %kernel.root_dir%/../web/images/club
        club_adapter_logo:
            local:
                directory: %kernel.root_dir%/../web/images/logo
        user_adapter_pict:
            local:
                directory: %kernel.root_dir%/../web/images/user
    filesystems:
        club_image_fs:
            adapter:    club_adapter_image
        club_logo_fs:
            adapter:    club_adapter_logo
        pict_user_fs:
            adapter:    user_adapter_pict


vich_uploader:
    db_driver:  orm
    storage: gaufrette 
    mappings:
        club_image:
            uri_prefix: images/club
            upload_destination: club_image_fs
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
        club_logo:
            uri_prefix: images/logo
            upload_destination: club_logo_fs
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
        user_pict:
            uri_prefix: images/user
            upload_destination: pict_user_fs
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            
liip_imagine:
    resolvers:
        default:
            web_path:
              web_root: ../web
              cache_prefix: media/cache 
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/ 
    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets:
        large:
            quality:              100
            filters:
                relative_resize: { heighten: 300, widen: 500, allow_upscale: true }
        grid:
            quality: 100
            filters:
                relative_resize: { heighten: 30, widen: 50, allow_upscale: true }


     