# app/config/security.yml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me : true
                always_use_default_target_path : true
                default_target_path: homepage
            logout:       true
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 1036800 # 4 mois

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN_SLAD }

    role_hierarchy:
        ROLE_PLAYER:        [ROLE_USER]
        ROLE_COACH:         [ROLE_PLAYER, ROLE_WRITER]
        ROLE_WRITER:        [ROLE_USER]
        ROLE_ADMIN:         [ROLE_COACH,ROLE_PLAYER,ROLE_USER]
        ROLE_PRESIDENT:     [ROLE_ADMIN]
        ROLE_ADMIN_SLAD:         [ROLE_PRESIDENT]
        ROLE_SUPER_ADMIN_SLAD:    [ROLE_ADMIN_SLAD, ROLE_WRITER, ROLE_ALLOWED_TO_SWITCH]
